### ISSUE TITLE
Review acuityscheduling.com

### ISSUE THREAD

**Issue by tkwon** [tkwon/appointments#1]
Sign up for free and check out their flow.

**Comment by kennymalac** [comment]
<img width="573" alt="screenshot_20170407_173241" src="https://cloud.githubusercontent.com/assets/1878648/24823976/662ae634-1bb9-11e7-94f3-147989349d8a.png">
<img width="415" alt="screenshot_20170407_173343" src="https://cloud.githubusercontent.com/assets/1878648/24823973/6614bbe8-1bb9-11e7-8a16-4eb5e4ee1f6d.png">
<img width="680" alt="screenshot_20170407_173426" src="https://cloud.githubusercontent.com/assets/1878648/24823977/662bbc8a-1bb9-11e7-9c9b-ead345968cdd.png">
<img width="324" alt="screenshot_20170407_173636" src="https://cloud.githubusercontent.com/assets/1878648/24823978/662eb64c-1bb9-11e7-8e8a-7f867e85856c.png">
<img width="583" alt="screenshot_20170407_173809" src="https://cloud.githubusercontent.com/assets/1878648/24823979/663001be-1bb9-11e7-8160-416078a2a2a3.png">
<img width="585" alt="screenshot_20170407_173909" src="https://cloud.githubusercontent.com/assets/1878648/24823974/661930c4-1bb9-11e7-87f4-b56a3c0ad789.png">
<img width="565" alt="screenshot_20170407_174010" src="https://cloud.githubusercontent.com/assets/1878648/24823975/662a90b2-1bb9-11e7-87e3-ba4d949f5bb2.png">
<img width="565" alt="screenshot_20170407_174010" src="https://cloud.githubusercontent.com/assets/1878648/24823984/79ec17b0-1bb9-11e7-8d22-7faf874dbd8e.png">
<img width="585" alt="screenshot_20170407_173909" src="https://cloud.githubusercontent.com/assets/1878648/24823985/79ec1d6e-1bb9-11e7-8cb4-1f718b99dbb3.png">
<img width="583" alt="screenshot_20170407_173809" src="https://cloud.githubusercontent.com/assets/1878648/24823986/79ec1a08-1bb9-11e7-9dd5-177b13853d35.png">
<img width="577" alt="screenshot_20170407_173725" src="https://cloud.githubusercontent.com/assets/1878648/24823987/79ec257a-1bb9-11e7-8ff7-01fb11225395.png">
<img width="324" alt="screenshot_20170407_173636" src="https://cloud.githubusercontent.com/assets/1878648/24823989/79ee7564-1bb9-11e7-9d3f-7aaf25dbf4c6.png">
<img width="680" alt="screenshot_20170407_173426" src="https://cloud.githubusercontent.com/assets/1878648/24823988/79ed0bb6-1bb9-11e7-90a0-b3f3eab86e52.png">
<img width="415" alt="screenshot_20170407_173343" src="https://cloud.githubusercontent.com/assets/1878648/24823991/7a028d9c-1bb9-11e7-9835-6c95f58dfd94.png">
<img width="573" alt="screenshot_20170407_173241" src="https://cloud.githubusercontent.com/assets/1878648/24823990/7a0232de-1bb9-11e7-830e-e7a99202bbc7.png">
