### ISSUE TITLE
Appointment/Event confirmations and rejections through AppointmentItemList

### ISSUE THREAD

**Issue by kennymalac** [tkwon/appointments#19]
Hovering over AppointmentItemList should highlight the corresponding event. (low priority)
Higher priority is confirms and rejects.

**Comment by kennymalac** [comment]
Fixed flux state tree so appointments are good to go. We filter by unconfirmed appointments.

**Comment by tkwon** [comment]
This issue was moved to tkwon/tru-academy#2492
