### ISSUE TITLE
Change CreateAppointmentModal into CRUDAppointmentModal

### ISSUE THREAD

**Issue by kennymalac** [tkwon/appointments#23]
When clicking on a calendar event/appointment, a user should be able to view the Appointment details, modify its state, or delete the appointment. All of this should be available in the CRUDAppointmentModal.

Request appointment (create) -> "Request" instead of submit
Modify appointment (update) -> "Save" instead of submit. Save button should be disabled until a change to the form state is detected. Make sure changing the date qualifies as a Move action.
Delete appointment (delete) -> "Delete" button in red color. Make sure to have a confirmation dialog.

**Comment by tkwon** [comment]
This issue was moved to tkwon/tru-academy#2496
