### ISSUE TITLE
Scheduling API

### ISSUE THREAD

**Issue by kennymalac** [tkwon/appointments#4]
GET /calendar/\<id\>/schedule/?year=YYYY?month=(0-12)

OUT:
```
{
  "next": "/calendar/<id>/schedule/?year=YYYY?month=(0-12+1)
  "previous": "/calendar/<id>/schedule/?year=YYYY?month=(0-12-1)",
  "availabilities": [
    ... sorted by date
  ],
  "appointments": [
    ... sorted by date
  ]
}
```

**Comment by kennymalac** [comment]
GET /calendar/\<id\>/schedule/\<year\>/\<month\>/\<week\>

OUT:
```
{
  "next": "/calendar/<id>/schedule/<year>/<month>/<week+1>",
  "previous": "/calendar/<id>/schedule/<year>/<month>/<week-1>",
  "availabilities": [
    ... sorted by date
  ],
  "appointments": [
    ... sorted by date
  ]
}
```

**Comment by kennymalac** [comment]
Changed to the following for better compatibility with FullCalendar.

GET /calendar/\<id\>/appointments/?start_time=\<YYYY-MM-DD\>?end_time=\<YYYY-MM-DD\>
OUT:
```
{
  result: [
    {appointment}, ...
  ]
}
```

GET /calendar/\<id\>/availabilities/?start_time=\<YYYY-MM-DD\>?end_time=\<YYYY-MM-DD\>
OUT:
```
{
  result: [
    {availability}, ...
  ]
}
```

**Comment by kennymalac** [comment]
https://github.com/tkwon/appointments/commit/c2a2e7318e1522696a049be083674881f837dc79

Fixed the serializers and updated ViewSet router URIs

**Comment by tkwon** [comment]
This issue was moved to tkwon/tru-academy#2484
