### ISSUE TITLE
Fullcalendar integration with Appointment

### ISSUE THREAD

**Issue by kennymalac** [tkwon/appointments#7]
TODO fill this in

**Comment by kennymalac** [comment]
Progress has been made in an implementation of FullCalendar. Custom UI buttons have been designed for the drag and drop interface but getting the code to compile suffered from a setback in an incomplete build suite.
BetterCalendar will be documented in this issue's description

**Comment by tkwon** [comment]
This issue was moved to tkwon/tru-academy#2485
